blank_issues_enabled: false

contact_links:

* name: 💬 VoidForge Studios Discord
  url: https://discord.gg/5Yya36GPyA
  about: Join our Discord to ask questions, discuss ideas, get help, and chat with the VoidForge Studios community.
